# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  set("KWWidgets_LIB_DEPENDS" "general;vtkCommonTCL;general;vtkRenderingTCL;general;vtkHybridTCL;general;vtkWidgetsTCL;general;vtkVolumeRenderingTCL;general;vtkpng;")
else()
  # Information for CMake 2.4 and lower.
  set("KWWidgets_LIB_DEPENDS" "vtkCommonTCL;vtkRenderingTCL;vtkHybridTCL;vtkWidgetsTCL;vtkVolumeRenderingTCL;vtkpng;")
endif()
