# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget itkdouble-conversion itksys itkvcl itkv3p_netlib itkv3p_lsqr itkvnl itkvnl_algo ITKVNLInstantiation ITKCommon itkNetlibSlatec ITKStatistics ITKIOImageBase ITKMesh itkzlib ITKMetaIO ITKSpatialObjects ITKPath ITKLabelMap ITKQuadEdgeMesh ITKOptimizers ITKPolynomials ITKBiasCorrection ITKBioCell ITKDICOMParser ITKEXPAT ITKIOXML ITKIOSpatialObjects ITKFEM ITKIOBMP ITKIOBioRad itkopenjpeg gdcmjpeg8 gdcmjpeg12 gdcmjpeg16 gdcmuuid gdcmCommon gdcmDICT gdcmDSED gdcmIOD gdcmMSFF ITKIOGDCM ITKIOIPL ITKIOGE ITKIOGIPL itkjpeg ITKIOJPEG ITKIOMeta ITKznz ITKniftiio ITKIONIFTI ITKNrrdIO ITKIONRRD itkpng ITKIOPNG ITKIOSiemens ITKIOStimulate itktiff ITKIOTIFF ITKIOTransformBase itkhdf5 itkhdf5_cpp ITKIOTransformHDF5 ITKIOTransformInsightLegacy ITKIOTransformMatlab ITKIOVTK ITKKLMRegionGrowing ITKIOLSM itkTestDriver ITKVTK ITKWatersheds ITKDeprecated ITKgiftiio ITKIOCSV ITKIOHDF5 ITKIOMRC ITKIOMesh ITKReview ITKVideoCore ITKVideoIO)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target itkdouble-conversion
add_library(itkdouble-conversion SHARED IMPORTED)

# Create imported target itksys
add_library(itksys SHARED IMPORTED)

# Create imported target itkvcl
add_library(itkvcl SHARED IMPORTED)

# Create imported target itkv3p_netlib
add_library(itkv3p_netlib SHARED IMPORTED)

# Create imported target itkv3p_lsqr
add_library(itkv3p_lsqr SHARED IMPORTED)

# Create imported target itkvnl
add_library(itkvnl SHARED IMPORTED)

# Create imported target itkvnl_algo
add_library(itkvnl_algo SHARED IMPORTED)

# Create imported target ITKVNLInstantiation
add_library(ITKVNLInstantiation SHARED IMPORTED)

# Create imported target ITKCommon
add_library(ITKCommon SHARED IMPORTED)

# Create imported target itkNetlibSlatec
add_library(itkNetlibSlatec SHARED IMPORTED)

# Create imported target ITKStatistics
add_library(ITKStatistics SHARED IMPORTED)

# Create imported target ITKIOImageBase
add_library(ITKIOImageBase SHARED IMPORTED)

# Create imported target ITKMesh
add_library(ITKMesh SHARED IMPORTED)

# Create imported target itkzlib
add_library(itkzlib SHARED IMPORTED)

# Create imported target ITKMetaIO
add_library(ITKMetaIO SHARED IMPORTED)

# Create imported target ITKSpatialObjects
add_library(ITKSpatialObjects SHARED IMPORTED)

# Create imported target ITKPath
add_library(ITKPath SHARED IMPORTED)

# Create imported target ITKLabelMap
add_library(ITKLabelMap SHARED IMPORTED)

# Create imported target ITKQuadEdgeMesh
add_library(ITKQuadEdgeMesh SHARED IMPORTED)

# Create imported target ITKOptimizers
add_library(ITKOptimizers SHARED IMPORTED)

# Create imported target ITKPolynomials
add_library(ITKPolynomials SHARED IMPORTED)

# Create imported target ITKBiasCorrection
add_library(ITKBiasCorrection SHARED IMPORTED)

# Create imported target ITKBioCell
add_library(ITKBioCell SHARED IMPORTED)

# Create imported target ITKDICOMParser
add_library(ITKDICOMParser SHARED IMPORTED)

# Create imported target ITKEXPAT
add_library(ITKEXPAT SHARED IMPORTED)

# Create imported target ITKIOXML
add_library(ITKIOXML SHARED IMPORTED)

# Create imported target ITKIOSpatialObjects
add_library(ITKIOSpatialObjects SHARED IMPORTED)

# Create imported target ITKFEM
add_library(ITKFEM SHARED IMPORTED)

# Create imported target ITKIOBMP
add_library(ITKIOBMP SHARED IMPORTED)

# Create imported target ITKIOBioRad
add_library(ITKIOBioRad SHARED IMPORTED)

# Create imported target itkopenjpeg
add_library(itkopenjpeg SHARED IMPORTED)

# Create imported target gdcmjpeg8
add_library(gdcmjpeg8 SHARED IMPORTED)

# Create imported target gdcmjpeg12
add_library(gdcmjpeg12 SHARED IMPORTED)

# Create imported target gdcmjpeg16
add_library(gdcmjpeg16 SHARED IMPORTED)

# Create imported target gdcmuuid
add_library(gdcmuuid SHARED IMPORTED)

# Create imported target gdcmCommon
add_library(gdcmCommon SHARED IMPORTED)

# Create imported target gdcmDICT
add_library(gdcmDICT SHARED IMPORTED)

# Create imported target gdcmDSED
add_library(gdcmDSED SHARED IMPORTED)

# Create imported target gdcmIOD
add_library(gdcmIOD SHARED IMPORTED)

# Create imported target gdcmMSFF
add_library(gdcmMSFF SHARED IMPORTED)

# Create imported target ITKIOGDCM
add_library(ITKIOGDCM SHARED IMPORTED)

# Create imported target ITKIOIPL
add_library(ITKIOIPL SHARED IMPORTED)

# Create imported target ITKIOGE
add_library(ITKIOGE SHARED IMPORTED)

# Create imported target ITKIOGIPL
add_library(ITKIOGIPL SHARED IMPORTED)

# Create imported target itkjpeg
add_library(itkjpeg SHARED IMPORTED)

# Create imported target ITKIOJPEG
add_library(ITKIOJPEG SHARED IMPORTED)

# Create imported target ITKIOMeta
add_library(ITKIOMeta SHARED IMPORTED)

# Create imported target ITKznz
add_library(ITKznz SHARED IMPORTED)

# Create imported target ITKniftiio
add_library(ITKniftiio SHARED IMPORTED)

# Create imported target ITKIONIFTI
add_library(ITKIONIFTI SHARED IMPORTED)

# Create imported target ITKNrrdIO
add_library(ITKNrrdIO SHARED IMPORTED)

# Create imported target ITKIONRRD
add_library(ITKIONRRD SHARED IMPORTED)

# Create imported target itkpng
add_library(itkpng SHARED IMPORTED)

# Create imported target ITKIOPNG
add_library(ITKIOPNG SHARED IMPORTED)

# Create imported target ITKIOSiemens
add_library(ITKIOSiemens SHARED IMPORTED)

# Create imported target ITKIOStimulate
add_library(ITKIOStimulate SHARED IMPORTED)

# Create imported target itktiff
add_library(itktiff SHARED IMPORTED)

# Create imported target ITKIOTIFF
add_library(ITKIOTIFF SHARED IMPORTED)

# Create imported target ITKIOTransformBase
add_library(ITKIOTransformBase SHARED IMPORTED)

# Create imported target itkhdf5
add_library(itkhdf5 SHARED IMPORTED)

# Create imported target itkhdf5_cpp
add_library(itkhdf5_cpp SHARED IMPORTED)

# Create imported target ITKIOTransformHDF5
add_library(ITKIOTransformHDF5 SHARED IMPORTED)

# Create imported target ITKIOTransformInsightLegacy
add_library(ITKIOTransformInsightLegacy SHARED IMPORTED)

# Create imported target ITKIOTransformMatlab
add_library(ITKIOTransformMatlab SHARED IMPORTED)

# Create imported target ITKIOVTK
add_library(ITKIOVTK SHARED IMPORTED)

# Create imported target ITKKLMRegionGrowing
add_library(ITKKLMRegionGrowing SHARED IMPORTED)

# Create imported target ITKIOLSM
add_library(ITKIOLSM SHARED IMPORTED)

# Create imported target itkTestDriver
add_executable(itkTestDriver IMPORTED)

# Create imported target ITKVTK
add_library(ITKVTK SHARED IMPORTED)

# Create imported target ITKWatersheds
add_library(ITKWatersheds SHARED IMPORTED)

# Create imported target ITKDeprecated
add_library(ITKDeprecated SHARED IMPORTED)

# Create imported target ITKgiftiio
add_library(ITKgiftiio SHARED IMPORTED)

# Create imported target ITKIOCSV
add_library(ITKIOCSV SHARED IMPORTED)

# Create imported target ITKIOHDF5
add_library(ITKIOHDF5 SHARED IMPORTED)

# Create imported target ITKIOMRC
add_library(ITKIOMRC SHARED IMPORTED)

# Create imported target ITKIOMesh
add_library(ITKIOMesh SHARED IMPORTED)

# Create imported target ITKReview
add_library(ITKReview SHARED IMPORTED)

# Create imported target ITKVideoCore
add_library(ITKVideoCore SHARED IMPORTED)

# Create imported target ITKVideoIO
add_library(ITKVideoIO SHARED IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/ITKTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
